language: php

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true

before_install:
  - sudo apt-get update

before_script:
  - composer install --prefer-dist --no-interaction --no-progress 
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]] || [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then sudo cp tests/php7-pool.conf ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/; fi
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  - cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - sudo cp -f tests/travis-ci-apache-vhost /etc/apache2/sites-available/default
  - sudo cp -Rf . /var/www/tb.unit.test
  - sudo chmod 777 -R /var/www/
  - sudo service apache2 restart

notifications:
  slack: thirtybees:L2Dyesn7En8jZ008IUwCrMnl
script:
  - /var/www/tb.unit.test/tests/check_php_parse_errors.sh
  - php /var/www/tb.unit.test/install-dev/index_cli.php --language=en --country=us --domain=localhost --base_uri=/tb.unit.test --db_name=tb.unit.test --db_create=1 --name=tb.unit.test --password=123456789
  - cd /var/www/tb.unit.test/tests && bash getcomposer.sh && php composer.phar install --dev --no-interaction --no-progress && php vendor/bin/phpunit -c .
after_success:
  - travis_retry php /var/www/tb.unit.test/tests/vendor/bin/coveralls
